version: '3.9'
services:
  postgres:
    build:
      context: deploy/postgres
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    networks:
      - my-network
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_USER=${POSTGRES_SUPERUSER}
      - POSTGRES_PASSWORD=${POSTGRES_SUPERUSER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER} -p 5432" ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my-network
    ports:
      - "8080:8000"
    volumes:
      - ./:/web/

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge